# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-06-10 10:49
from __future__ import unicode_literals

import administration.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shortname', models.CharField(help_text='Abbreviation of a class', max_length=10, unique=True)),
                ('classtype', models.CharField(help_text='Class type: V, S, I or K...', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title at the main page', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(help_text='Temporary pin for specific user', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveSmallIntegerField(help_text='Which round of voting is it.')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('election_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.Election')),
            ],
        ),
        migrations.CreateModel(
            name='RoundType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='type', max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profile_image', models.FileField(help_text='Profile image', upload_to=administration.models.user_image_name)),
                ('class_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.Class')),
                ('pin_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='administration.Pin')),
            ],
        ),
        migrations.AddField(
            model_name='round',
            name='type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.RoundType'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='round_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administration.Round'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Student'),
        ),
    ]
